# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "centos/7"

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 60
  config.ssh.insert_key = false
  config.vm.box_check_update = true
  config.vm.provider :libvirt do |libvirt|
  # Don't forget to create your storage pool
    libvirt.storage_pool_name="default"
    libvirt.driver="kvm"
    libvirt.uri="qemu:///system"
  end
  config.vm.define :test_machine do |node|
    node.vm.box = box
    node.vm.network :private_network, ip: "10.10.10.11"
    node.vm.network :forwarded_port, guest: 22, host: 24011, auto_correct: true
    node.vm.provider "libvirt" do |d|
      d.memory = 2048
      d.graphics_type = "none"
      d.cpus = 2
    end
  end
end